name: HuggingChat-iOS
options:
  bundleIdPrefix: com.huggingface
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

packages:
  MLXSwift:
    url: https://github.com/ml-explore/mlx-swift
    branch: main
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit
    from: 0.9.0
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: 2.0.0
  GzipSwift:
    url: https://github.com/1024jp/GzipSwift
    from: 6.0.1
  PathSwift:
    url: https://github.com/mxcl/Path.swift
    from: 1.0.0
  SwiftTransformers:
    url: https://github.com/huggingface/swift-transformers
    from: 0.1.0
  Pow:
    url: https://github.com/EmergeTools/Pow
    from: 1.0.0

targets:
  HuggingChat-iOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - HuggingChat-iOS
    dependencies:
      - package: MLXSwift
        product: MLX
      - package: MLXSwift
        product: MLXNN
      - package: MLXSwift
        product: MLXRandom
      - package: MLXSwift
        product: MLXOptimizers
      - package: MLXSwift
        product: MLXFFT
      - package: MLXSwift
        product: MLXLinalg
      - package: WhisperKit
        product: WhisperKit
      - package: MarkdownUI
        product: MarkdownUI
      - package: GzipSwift
        product: Gzip
      - package: PathSwift
        product: Path
      - package: SwiftTransformers
        product: Transformers
      - package: Pow
        product: Pow
    info:
      path: HuggingChat-iOS/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.huggingface.HuggingChat-iOS
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "6.0"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        ENABLE_PREVIEWS: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

  HuggingChatKeyboard:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - HuggingChatKeyboard
    dependencies:
      - target: HuggingChat-iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.huggingface.HuggingChat-iOS.Keyboard

  HuggingChatWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - HuggingChatWidget
    dependencies:
      - target: HuggingChat-iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.huggingface.HuggingChat-iOS.Widget

  ShareExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - ShareExtension
    dependencies:
      - target: HuggingChat-iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.huggingface.HuggingChat-iOS.ShareExtension
